dam_dan_admin:
    resource: "@DamDanAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

dam_dan_user:
    resource: "@DamDanUserBundle/Controller/"
    type:     annotation
    prefix:   /

dam_dan_app:
    resource: "@DamDanAppBundle/Controller/"
    type:     annotation
    prefix:   /

dam_dan_user_logout:
    path: /logout
