security:
    encoders:
        DamDan\UserBundle\Entity\User:
            algorithm: bcrypt

    providers:
        db_provider:
            entity:
                class: DamDanUserBundle:User
                property: email

    firewalls:
        main:
            anonymous: ~
            provider: db_provider
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /login

    role_hierarchy:
            ROLE_EDITOR: ROLE_SERVER
            ROLE_REVIEWER: ROLE_EDITOR
            ROLE_CHEF: ROLE_REVIEWER

    access_control:
            - { path: ^/admin, roles: ROLE_SERVER }
            - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
