services:
    damdan.breadcrumb_extension:
        class: DamDan\AppBundle\Twig\BreadcrumbExtension
        public: false
        arguments: ['@router']
        tags:
            - { name: twig.extension }

    damdan.notify.listener:
            class: DamDan\AppBundle\EventListener\NotifySubscriber
            arguments: ['@templating', '@mailer', '%dandam_app.administrator.email%']

            tags:
                - { name: doctrine.event_subscriber, connection: default }

    damdan.image_uploader:
            class: DamDan\AppBundle\Services\FileUploader
            arguments: ['%dandam_app.upload_dir%']

    damdan.doctrine_dish_listener:
            class: DamDan\AppBundle\EventListener\ImageUploadListener
            arguments: ['@damdan.image_uploader']
            tags:
                - { name: doctrine.event_listener, event: prePersist }
                - { name: doctrine.event_listener, event: preUpdate }