services:
    damdan.breadcrumb_extension:
        class: DamDan\AppBundle\Twig\BreadcrumbExtension
        public: false
        arguments: ['@router']
        tags:
            - { name: twig.extension }

    damdan.notify.listener:
            class: DamDan\AppBundle\EventListener\NotifySubscriber
            arguments: ['@templating', '@mailer', '%dandam_app.administrator.email%']

            tags:
                - { name: doctrine.event_subscriber, connection: default }

    damdan.image_uploader:
            class: DamDan\AppBundle\Services\FileUploader
            arguments: ['%dandam_app.upload_dir%']

    damdan.paginator:
            class: DamDan\AppBundle\Services\Paginator

    damdan.doctrine_dish_listener:
            class: DamDan\AppBundle\EventListener\ImageUploadListener
            arguments: ['@damdan.image_uploader']
            tags:
                - { name: doctrine.event_listener, event: prePersist }
                - { name: doctrine.event_listener, event: preUpdate }

    damdan.reservation.listener:
            class: DamDan\AppBundle\EventListener\ReservationSubscriber
            arguments: ['@templating', '@mailer', '%dandam_app.administrator.email%']
            tags:
                - { name: doctrine.event_subscriber, connection: default }

    damdan.form.type.dish:
            class: DamDan\AppBundle\Form\Type\DishType
            arguments: ["@security.authorization_checker"]
            tags:
                - { name: form.type, alias: damdan_dish_type }

    damdan.form.type.menu:
                class: DamDan\AppBundle\Form\Type\MenuType
                arguments: ["@security.authorization_checker"]
                tags:
                    - { name: form.type, alias: damdan_menu_type }
