services:
    damdan.breadcrumb_extension:
        class: DamDan\AppBundle\Twig\BreadcrumbExtension
        public: false
        arguments: ['@router']
        tags:
            - { name: twig.extension }
