services:
    damdan.breadcrumb_extension:
        class: DamDan\AppBundle\Twig\BreadcrumbExtension
        public: false
        arguments: ['@router']
        tags:
            - { name: twig.extension }

    damdan.notify.listener:
            class: DamDan\AppBundle\EventListener\NotifySubscriber
            arguments: ['@templating', '@mailer', '%dandam_app.administrator.email%']

            tags:
                - { name: doctrine.event_subscriber, connection: default }