<?php

namespace DamDan\UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByRole($role){
        $users = $this->findAll();
        $usersWithRole = [];

        foreach($users as $user){
            if(in_array($role, $user->getRoles())){
                $usersWithRole[] = $user;
            }
        }

        return $usersWithRole;
    }

}
