<?php

namespace DamDan\AppBundle\Repository;

/**
 * AllergenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AllergenRepository extends \Doctrine\ORM\EntityRepository
{
}
