<?php

namespace DamDan\AppBundle\Repository;

/**
 * DishRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DishRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByNotStatus($status){
        $qb = $this->createQueryBuilder('d');
        return $qb->select('d')
            ->where($qb->expr()->notIn('d.status', [$status]))
            ->getQuery()
            ->getResult();
    }
}
